# Generated by Django 3.2 on 2021-12-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.IntegerField(default=0)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party1', to='accounts.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party2', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='dummy', max_length=500)),
                ('sender_user', models.CharField(default='dummy', max_length=500)),
                ('receiver_user', models.CharField(default='dummy', max_length=500)),
                ('socket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.socket')),
            ],
        ),
    ]
